### ISSUE TITLE
Market takers sometimes returning to original AUM at the end of sim

### ISSUE THREAD

**Issue by avocardio** [QMResearch/qmrExchange#3]
Went through the source, but couldn't find what's causing this. This is only the case when using more than one market taker in the sim. 

![Figure_1](https://user-images.githubusercontent.com/74978236/193658038-346ab5f2-415c-4ad5-8349-d63e96772fbe.png)
![Figure_2](https://user-images.githubusercontent.com/74978236/193658034-1c6b101a-4c6e-4d9d-bec8-6dcb7ed500f2.png)

In the images above, all market takers where instantiated at AUM of 100. 

Any idea of what might be causing this?

**Comment by martinnmayer** [comment]
I just tested it and was able to replicate the issue. Thank you very much for bringing it up. I'll definitely check out what is causing it and fix it!

**Comment by martinnmayer** [comment]
Thanks for bringing up this issue!
I have fixed this issue in: 77d43e8d492f1d352a2ebbcc1d8514687c8de6d4

**Comment by avocardio** [comment]
Thanks, very cool project btw. Is it open for contributions?

**Comment by martinnmayer** [comment]
> Thanks, very cool project btw. Is it open for contributions?

Thanks for the feedback! Yes, the project is open to contributions from other developers!
